name: Update GitHub Profile 3D

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间凌晨0点自动运行
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Profile 3D
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: EchoLumi
