name: Generate 3D Contribution

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC 生成
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D
        uses: yoshi389111/github-profile-3d-contrib@0.8.1
        with:
          USERNAME: EchoLumi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3d contributions"
          git push
